### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by IvoWalach** [sampatbadhe/isbndb-ruby#6]
Hey,
when I try to follow your steps, and then call some method (for example isbndb_api_client.stats), I get an error "uninitialized constant ISBNdb::ApiClient::Addressable". I tried everything, but nothing worked. What should i do?

**Comment by sampatbadhe** [comment]
Hey @IvoWalach 

Thank you for reporting the issue. In the most recent version, we changed `URI.escape` to `Addressable::URI.encode` in #5  which requires [addressable gem](https://github.com/sporkmonger/addressable) to encode the URI.

**Comment by sampatbadhe** [comment]
Hey @IvoWalach 

I made the fix and released the changes in new version `0.1.3`.
